# Generated by Django 3.1 on 2020-09-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
    ]
