# Generated by Django 3.1 on 2020-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_pass',
            field=models.DateTimeField(verbose_name='Last Pass'),
        ),
    ]
