# Generated by Django 3.1 on 2020-09-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_pass',
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.employee')),
            ],
        ),
    ]
