# Generated by Django 3.1 on 2020-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200929_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name': 'Pass History', 'verbose_name_plural': 'Pass Histories'},
        ),
        migrations.AlterField(
            model_name='pass',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start',
            field=models.DateField(),
        ),
    ]
