# Generated by Django 3.1 on 2020-08-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permanent_address',
        ),
    ]
